USE 2022_pbzm_nino_curin;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS POSTA;
DROP TABLE IF EXISTS NASLOV;
DROP TABLE IF EXISTS OSEBA;
DROP TABLE IF EXISTS DELAVEC;
DROP TABLE IF EXISTS LOKAL;
DROP TABLE IF EXISTS KATEGORIJA_LOKALA;
DROP TABLE IF EXISTS TERMINALI;
DROP TABLE IF EXISTS PREVZEMANJE_PRTLJAGE;
DROP TABLE IF EXISTS PRTLJAGA;
DROP TABLE IF EXISTS VARNOST;
DROP TABLE IF EXISTS KARTA;
DROP TABLE IF EXISTS POLET;
DROP TABLE IF EXISTS VRATA;
DROP TABLE IF EXISTS LETALISCE;
DROP TABLE IF EXISTS AVION;
DROP TABLE IF EXISTS AIRLINE;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE POSTA (
	idPosta INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    naziv_poste VARCHAR(45) NOT NULL,
    st_poste VARCHAR(45) NOT NULL
);
CREATE TABLE NASLOV (
	idNaslov INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ulica VARCHAR(45) NOT NULL,
    hisna_st VARCHAR(45) NOT NULL,
    Pošta_idPošta INT NOT NULL
);
CREATE TABLE OSEBA (
	idOseba INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	Ime VARCHAR(45) NOT NULL,
	Priimek VARCHAR(45) NOT NULL,
	Adresa_pribivalistva VARCHAR(45) NOT NULL,
	St_telefona VARCHAR(45),
	Daucna_st VARCHAR(45) NOT NULL,
	Emsa VARCHAR(45) NOT NULL, 
	Email VARCHAR(45),
	idKarta INT NOT NULL,
	Delavec_idDelavec INT NOT NULL,
	Naslov_idNaslov INT NOT NULL
);
CREATE TABLE DELAVEC (
	idDelavec INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	datum_od DATE NOT NULL,
	datum_do DATE NOT NULL,
    ime_delavca VARCHAR (45) NOT NULL,
    priimek_delavca VARCHAR (45) NOT NULL
);
CREATE TABLE LOKAL (
	idDodtna_podjetja INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Ime_lokala VARCHAR(45) NOT NULL,
	Ime_Lastnika VARCHAR(45), 
	Otpiralni_cas VARCHAR(45) NOT NULL,
	Zapiralni_cas VARCHAR(45) NOT NULL,
	Terminali_idTerminali INT NOT NULL,
	Kategorija_lokala_idKategorija_lokala INT NOT NULL,
	Delavec_idDelavec INT NOT NULL
);
CREATE TABLE KATEGORIJA_LOKALA (
	idKategorija_lokala INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	naziv VARCHAR(45) NOT NULL
);
CREATE TABLE TERMINALI (
	idTerminali INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	St_Terminala VARCHAR(45) NOT NULL
);
CREATE TABLE PREVZEMANJE_PRTLJAGE (
	idPrevzemanje_Prtljage INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Ime_sektorja VARCHAR(45) NOT NULL,
	Terminali_idTerminali INT NOT NULL
);
CREATE TABLE PRTLJAGA (
	idPrtljaga INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Velikost VARCHAR(45) NOT NULL,
	Utez VARCHAR(45) NOT NULL,
	Oseba_idOseba INT NOT NULL,
	Oseba_Pošta_idPošta INT NOT NULL,
	Prevzemanje_Prtljage_idPrevzemanje_Prtljage INT NOT NULL
);
CREATE TABLE VARNOST (
	idVarnost INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Cas_otpiranja VARCHAR(45) NOT NULL,
	Cas_zapiranja VARCHAR(45) NOT NULL, 
	Vrsta_varnosti VARCHAR(45) NOT NULL,
	Terminali_idTerminali INT NOT NULL
);
CREATE TABLE KARTA (
	idPrijave INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	St_karte VARCHAR(45) NOT NULL,
	St_prtljage VARCHAR(45) NOT NULL,
	Uznaka_prtljage VARCHAR(45) NOT NULL,
	Terminali_idTerminali INT NOT NULL,
	Polet_idPolet INT NOT NULL
);
CREATE TABLE  POLET (
	idPolet INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Čas_prihoda VARCHAR(45) NOT NULL,
	Čas_odhoda VARCHAR(45) NOT NULL,
	Datum_prihoda VARCHAR(45) NOT NULL,
	Datum_odhoda VARCHAR(45) NOT NULL,
	Mesto_prihoda VARCHAR(45) NOT NULL,
	Mesto_odhoda VARCHAR(45) NOT NULL,
	Čas_leta VARCHAR(45) NOT NULL,
	Vrata_idVrata INT NOT NULL,
	Avion_idAvion INT NOT NULL,
	st_leta INT NOT NULL,
	Letalisce_idLetalisce INT NOT NULL
);
CREATE TABLE VRATA (
	idVrata INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	St_Vrat VARCHAR(45) NOT NULL,
	Terminali_idTerminali INT NOT NULL
);
CREATE TABLE LETALISCE (
	idLetalisce INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	naziv VARCHAR(45) NOT NULL
);
CREATE TABLE AVION (
	idAvion INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Ime_model VARCHAR(45) NOT NULL,
	Proizvajalec VARCHAR(45) NOT NULL,
	St_sedeza VARCHAR(45),
	Leto_proizodnje VARCHAR(45),
	Makismalna_teza VARCHAR(45)
);
CREATE TABLE AIRLINE (
	idAirline INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Ime_airline VARCHAR(45)  NOT NULL,
	Tip_airline VARCHAR(45)  NOT NULL,
	St_Avionov VARCHAR(45),
	Avion_idAvion INT  NOT NULL
);

ALTER TABLE NASLOV ADD CONSTRAINT tk_naslov_posta FOREIGN KEY (Pošta_idPošta) REFERENCES POSTA (idPosta) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE OSEBA ADD CONSTRAINT tk_oseba_karta FOREIGN KEY (idKarta) REFERENCES KARTA (idPrijave) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE OSEBA ADD CONSTRAINT tk_oseba_delavec FOREIGN KEY (Delavec_idDelavec) REFERENCES DELAVEC (idDelavec) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE OSEBA ADD CONSTRAINT tk_oseba_naslov FOREIGN KEY (Naslov_idNaslov) REFERENCES NASLOV (idNaslov) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE PRTLJAGA ADD CONSTRAINT tk_prtljaga_oseba FOREIGN KEY (Oseba_idOseba) REFERENCES OSEBA (idOseba) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE PRTLJAGA ADD CONSTRAINT tk_prtljaga_posta FOREIGN KEY (Oseba_Pošta_idPošta ) REFERENCES POSTA (idPosta) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE PRTLJAGA ADD CONSTRAINT tk_prtljaga_prevzemanje_prtljage FOREIGN KEY (Prevzemanje_Prtljage_idPrevzemanje_Prtljage) REFERENCES PREVZEMANJE_PRTLJAGE (idPrevzemanje_Prtljage) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE PREVZEMANJE_PRTLJAGE ADD CONSTRAINT tk_prevzemanje_prtljage_terminali FOREIGN KEY (Terminali_idTerminali) REFERENCES TERMINALI (idTerminali) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE LOKAL ADD CONSTRAINT tk_lokal_terminali FOREIGN KEY (Terminali_idTerminali) REFERENCES POSTA (idPosta) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE LOKAL ADD CONSTRAINT tk_lokal_kategorija_lokala FOREIGN KEY (Kategorija_lokala_idKategorija_lokala) REFERENCES KATEGORIJA_LOKALA (idKategorija_lokala) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE LOKAL ADD CONSTRAINT tk_lokal_delavec FOREIGN KEY (Delavec_idDelavec) REFERENCES DELAVEC (idDelavec) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE VARNOST ADD CONSTRAINT tk_varnost_terminali FOREIGN KEY (Terminali_idTerminali) REFERENCES TERMINALI (idTerminali) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE KARTA ADD CONSTRAINT tk_karta_terminali FOREIGN KEY (Terminali_idTerminali) REFERENCES TERMINALI (idTerminali) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE KARTA ADD CONSTRAINT tk_karta_polet FOREIGN KEY (Polet_idPolet) REFERENCES POLET (idPOLET) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE POLET ADD CONSTRAINT tk_polet_vrata FOREIGN KEY (Vrata_idVrata) REFERENCES VRATA (idVrata) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE POLET ADD CONSTRAINT tk_polet_avion FOREIGN KEY (Avion_idAvion) REFERENCES AVION (idAVion) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE POLET ADD CONSTRAINT tk_polet_letalisce FOREIGN KEY (Letalisce_idLetalisce) REFERENCES LETALISCE (idLetalisce) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE AIRLINE ADD CONSTRAINT tk_airline_avion FOREIGN KEY (Avion_idAvion) REFERENCES AVION (idAVion) ON UPDATE CASCADE ON DELETE RESTRICT;
	
INSERT INTO POSTA VALUES(NULL, 'Maribor', 4000);
INSERT INTO POSTA VALUES(NULL, 'Štrigova', 1000);
INSERT INTO POSTA VALUES(NULL, 'Macinec', 5000);
INSERT INTO POSTA VALUES(NULL, 'Čakovec', 6000);
INSERT INTO POSTA VALUES(NULL, 'Zagreb', 8000);

INSERT INTO DELAVEC VALUES(NULL, '2011-3-11', '2012-6-13', 'Nino', 'Čurin');
INSERT INTO DELAVEC VALUES(NULL, '2012-5-15', '2016-2-1', 'Pero', 'Perovski');
INSERT INTO DELAVEC VALUES(NULL, '2011-2-6', '2011-8-16', 'Kero', 'Keretič');
INSERT INTO DELAVEC VALUES(NULL, '2014-6-23', '2017-6-21', 'Miki', 'Mikić');
INSERT INTO DELAVEC VALUES(NULL, '2009-5-1', '2014-2-14', 'Piki', 'Pikić');

INSERT INTO KATEGORIJA_LOKALA VALUES(NULL, 'Pub');
INSERT INTO KATEGORIJA_LOKALA VALUES(NULL, 'Trgovina');
INSERT INTO KATEGORIJA_LOKALA VALUES(NULL, 'Resotran');
INSERT INTO KATEGORIJA_LOKALA VALUES(NULL, 'Bar');
INSERT INTO KATEGORIJA_LOKALA VALUES(NULL, 'Pekara');

INSERT INTO TERMINALI VALUES(NULL, '1');
INSERT INTO TERMINALI VALUES(NULL, '2');
INSERT INTO TERMINALI VALUES(NULL, '3');
INSERT INTO TERMINALI VALUES(NULL, '4');
INSERT INTO TERMINALI VALUES(NULL, '5');

INSERT INTO LETALISCE VALUES(NULL, 'Letalisce Maksimir');
INSERT INTO LETALISCE VALUES(NULL, 'Letalisce Maksimirović');
INSERT INTO LETALISCE VALUES(NULL, 'Letalisce Zanzibar');
INSERT INTO LETALISCE VALUES(NULL, 'Letalisce Čurin');
INSERT INTO LETALISCE VALUES(NULL, 'Letalisce Astral');

INSERT INTO AVION VALUES(NULL, 'AR-13', 'Millenium Industries', 43, 2012, '8000kg');
INSERT INTO AVION VALUES(NULL, 'AR-12', 'Millenium Industries', 43, 2003, '6000kg');
INSERT INTO AVION VALUES(NULL, 'AB-1', 'Stark Industries', 43, 2010, '7000kg');
INSERT INTO AVION VALUES(NULL, 'BR-3', 'Stark Industries', 43, 2015, '7500kg');
INSERT INTO AVION VALUES(NULL, 'VC-333', 'Ferit Industries', 43, 2006, '7300kg');

INSERT INTO NASLOV VALUES(NULL, 'Prhovec', 8, 1);
INSERT INTO NASLOV VALUES(NULL, 'Šentilj', 6, 2);
INSERT INTO NASLOV VALUES(NULL, 'Maribor', 4, 3);
INSERT INTO NASLOV VALUES(NULL, 'Zagreb', 3, 4);
INSERT INTO NASLOV VALUES(NULL, 'Karlovac', 32, 5);
INSERT INTO NASLOV VALUES(NULL, 'Prhovec', 22, 1);
INSERT INTO NASLOV VALUES(NULL, 'Badličan', 6, 1);
INSERT INTO NASLOV VALUES(NULL, 'Preseka', 8, 2);
INSERT INTO NASLOV VALUES(NULL, 'Čakovec', 8, 3);
INSERT INTO NASLOV VALUES(NULL, 'Prhovec', 8, 4);

INSERT INTO VRATA VALUES(NULL, 1, 1);
INSERT INTO VRATA VALUES(NULL, 2, 2);
INSERT INTO VRATA VALUES(NULL, 3, 3);
INSERT INTO VRATA VALUES(NULL, 4, 4);
INSERT INTO VRATA VALUES(NULL, 5, 5);
INSERT INTO VRATA VALUES(NULL, 6, 1);
INSERT INTO VRATA VALUES(NULL, 7, 2);
INSERT INTO VRATA VALUES(NULL, 8, 3);
INSERT INTO VRATA VALUES(NULL, 9, 4);
INSERT INTO VRATA VALUES(NULL, 10, 5);

INSERT INTO POLET VALUES(NULL, '08:00', '10:00', '11.3.2011', '11.3.2013', 'Ljubljana', 'Antwerp', '2h', 1, 1, 4, 1);
INSERT INTO POLET VALUES(NULL, '12:00', '14:00', '11.3.2011', '11.3.2013', 'Ljubljana', 'Brussels', '2h', 2, 2, 78, 2);
INSERT INTO POLET VALUES(NULL, '17:00', '20:00', '11.3.2011', '11.3.2013', 'Zagreb', 'Antwerp', '3h', 3, 3, 64, 3);
INSERT INTO POLET VALUES(NULL, '08:00', '10:00', '12.3.2011', '12.3.2013', 'Zagreb', 'Brussels', '2h', 4, 4, 43, 4);
INSERT INTO POLET VALUES(NULL, '12:00', '14:00', '12.3.2011', '12.3.2013', 'Zagreb', 'Amsterdam', '2h', 5, 5, 57, 5);
INSERT INTO POLET VALUES(NULL, '17:00', '20:00', '12.3.2011', '12.3.2013', 'Zagreb', 'Essen', '3h', 6, 1, 33, 1);
INSERT INTO POLET VALUES(NULL, '08:00', '10:00', '13.3.2011', '13.3.2013', 'Zagreb', 'Roterdam', '2h', 7, 2, 65, 2);
INSERT INTO POLET VALUES(NULL, '12:00', '14:00', '13.3.2011', '13.3.2013', 'Zagreb', 'Antwerp', '2h', 8, 3, 85, 3);
INSERT INTO POLET VALUES(NULL, '17:00', '20:00', '13.3.2011', '13.3.2013', 'Zagreb', 'London', '3h', 9, 4, 73, 4);
INSERT INTO POLET VALUES(NULL, '08:00', '10:00', '14.3.2011', '14.3.2013', 'Zagreb', 'Lepizig', '2h', 10, 5, 83, 5);

INSERT INTO KARTA VALUES(NULL, 003565,004324, 'luggage', 1, 1);
INSERT INTO KARTA VALUES(NULL, 004363,002278, 'case', 2, 2);
INSERT INTO KARTA VALUES(NULL, 003463,004532, 'big case', 3, 3);
INSERT INTO KARTA VALUES(NULL, 002545,007382, 'big case', 4, 4);
INSERT INTO KARTA VALUES(NULL, 001345,007356, 'backpack', 5, 5);
INSERT INTO KARTA VALUES(NULL, 002603,005372, 'laptop case', 1, 6);
INSERT INTO KARTA VALUES(NULL, 002023,004325, 'backpack', 2, 7);
INSERT INTO KARTA VALUES(NULL, 006434,000231, 'luggage', 3, 8);
INSERT INTO KARTA VALUES(NULL, 002222,004012, 'case', 4, 9);
INSERT INTO KARTA VALUES(NULL, 002343,001247, 'backpack + luggage', 5, 10);

INSERT INTO OSEBA VALUES(NULL, 'Nino', 'Čurin', 'Prhovec 8', '+385 99 122 6353', '387563252358', '723557975', 'nino@gmail.com', 1, 1, 1);
INSERT INTO OSEBA VALUES(NULL, 'Pero', 'Perovski', 'Šentilj 6', '+386 99 232 5343', 38764368658, 753957975, 'pero@gmail.com', 2, 2, 2);
INSERT INTO OSEBA VALUES(NULL, 'Kero', 'Keretič', 'Maribor 4', '+386 99 832 4943', 385342338658, 53253957975, 'ker@gmail.com', 3, 3, 3);
INSERT INTO OSEBA VALUES(NULL, 'Miki', 'Mikić', 'Zagreb 3', '+385 99 871 6969', 387562328, 3235529575, 'miki@gmail.com', 4, 4, 4);
INSERT INTO OSEBA VALUES(NULL, 'Piki', 'Pikić', 'Karlovac 32', '+385 99 072 6999', 385325328658, 753957975, 'piki@gmail.com', 5, 5, 5);
INSERT INTO OSEBA VALUES(NULL, 'Riki', 'Novak', 'Prhovec 6', '+385 99 872 6900', 387565235658, 55395797325, 'riki@gmail.com', 6, 1, 6);
INSERT INTO OSEBA VALUES(NULL, 'Lukec', 'Modrić', 'Badličan 8', '+385 99 072 5394', 3875638658, 532395797, 'lukec@gmail.com', 7, 2, 7);
INSERT INTO OSEBA VALUES(NULL, 'Joško', 'Novak', 'Preseka 8', '+385 99 870 6953', 253525638658, 7539572352, 'josko@gmail.com', 8, 3, 8);
INSERT INTO OSEBA VALUES(NULL, 'Franjo', 'Muljkić', 'Čakovec 8', '+385 99 832 4942', 353235275638658, 7533255, 'franjo@gmail.com', 9, 4, 9);
INSERT INTO OSEBA VALUES(NULL, 'Borna', 'Kečap', 'Prhovec 8', '+385 99 542 6043', 38753252358, 23523357975, 'borna@gmail.com', 10, 5, 10);

INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector A', 1);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector B', 2);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector C', 3);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector D', 4);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector E', 5);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector F', 1);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector G', 2);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector H', 3);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector J', 4);
INSERT INTO PREVZEMANJE_PRTLJAGE VALUES(NULL, 'sector K', 5);

INSERT INTO PRTLJAGA VALUES(NULL, '33x60cm', '9.3kg', 1, 1, 1);
INSERT INTO PRTLJAGA VALUES(NULL, '32x56cm', '9.1kg',  2, 2, 2);
INSERT INTO PRTLJAGA VALUES(NULL, '34x63cm', '8.9kg', 3, 3, 3);
INSERT INTO PRTLJAGA VALUES(NULL, '20x49cm', '5.3kg', 4, 4, 4);
INSERT INTO PRTLJAGA VALUES(NULL, '16x45cm', '4.9kg', 5, 5, 5);
INSERT INTO PRTLJAGA VALUES(NULL, '30x53cm', '8.2kg', 6, 1, 6);
INSERT INTO PRTLJAGA VALUES(NULL, '33x62cm', '9.02kg', 7, 2, 7);
INSERT INTO PRTLJAGA VALUES(NULL, '28x57cm', '7.5kg', 8, 3, 8);
INSERT INTO PRTLJAGA VALUES(NULL, '26x54cm', '6.9kg', 9, 4, 9);
INSERT INTO PRTLJAGA VALUES(NULL, '34x63cm', '9kg', 10, 5, 10);

INSERT INTO LOKAL VALUES(NULL, 'Potkovina Pub', 'Pero', '08:00', '23:00', 1, 1, 1);
INSERT INTO LOKAL VALUES(NULL, 'W-BAR', 'Raketič', '08:00', '20:00', 2, 2, 2);
INSERT INTO LOKAL VALUES(NULL, 'Restoran quelle', 'Livaković', '08:00', '23:00', 3, 3, 2);
INSERT INTO LOKAL VALUES(NULL, 'Restoran oui-oui', 'Mislav', '08:00', '23:00', 4, 4, 4);
INSERT INTO LOKAL VALUES(NULL, 'Bar Botra', 'Božidar', '08:00', '21:00', 5, 5, 5);
INSERT INTO LOKAL VALUES(NULL, 'Los Pollos Hermanos', 'Mario', '07:00', '21:00', 1, 1, 2);
INSERT INTO LOKAL VALUES(NULL, 'Tisak media centra', 'Jožica', '09:00', '21:00', 2, 2, 3);
INSERT INTO LOKAL VALUES(NULL, 'Ljubljancek', 'Kristijan', '09:00', '21:00', 3, 3, 2);
INSERT INTO LOKAL VALUES(NULL, 'Pekara Miki', 'Josip', '08:00', '23:00', 4, 4, 3);
INSERT INTO LOKAL VALUES(NULL, 'Metss', 'Micika', '08:00', '23:00', 5, 5, 5);

INSERT INTO VARNOST VALUES(NULL, '00:00', '00:00', 'Search', 1);
INSERT INTO VARNOST VALUES(NULL, '00:00', '00:00', 'Search', 2);
INSERT INTO VARNOST VALUES(NULL, '00:00', '00:00', 'Search', 3);
INSERT INTO VARNOST VALUES(NULL, '00:00', '00:00', 'Search', 4);
INSERT INTO VARNOST VALUES(NULL, '05:00', '23:00', 'Special Search', 5);
INSERT INTO VARNOST VALUES(NULL, '05:00', '23:00', 'Special Search', 1);
INSERT INTO VARNOST VALUES(NULL, '00:00', '00:00', 'Search', 2);
INSERT INTO VARNOST VALUES(NULL, '00:00', '00:00', 'Search', 3);
INSERT INTO VARNOST VALUES(NULL, '12:00', '23:00', 'Flight crew Search', 4);
INSERT INTO VARNOST VALUES(NULL, '00:00', '00:00', 'Search', 5);

INSERT INTO AIRLINE VALUES(NULL, 'Slovenia Airlines', 'legacy', '50', 1);
INSERT INTO AIRLINE VALUES(NULL, 'Slovenia Airlines', 'legacy', '42', 2);
INSERT INTO AIRLINE VALUES(NULL, 'Croatia Airlines', 'legacy', '48', 3);
INSERT INTO AIRLINE VALUES(NULL, 'Swiss International', 'legacy', '30', 4);
INSERT INTO AIRLINE VALUES(NULL, 'Belgian Airlines', 'low cost carriers', '60', 5);
INSERT INTO AIRLINE VALUES(NULL, 'Brussels Airlines', 'legacy', '40', 1);
INSERT INTO AIRLINE VALUES(NULL, 'Croatia Airlines', 'legacy', '42', 2);
INSERT INTO AIRLINE VALUES(NULL, 'Croatia Airlines', 'legacy', '48', 3);
INSERT INTO AIRLINE VALUES(NULL, 'Netherlands Airlines', 'legacy', '42', 4);
INSERT INTO AIRLINE VALUES(NULL, 'Croatia Airlines', 'low cost carriers', '66', 5);

#1.
#SELECT ime,priimek FROM OSEBA;

#2.
#SELECT ime_lokala FROM LOKAL;

#3.
#SELECT ime,priimek,datum_od,datum_do, DATEDIFF(datum_do, datum_od) AS Dni_zaposlitve FROM OSEBA,DELAVEC WHERE Delavec_idDelavec = idDelavec;

#5.
SELECT MAX(maks) AS najvec_letov
FROM( 
        SELECT Ime_model, MAX(st_leta) AS maks
         FROM AVION,POLET WHERE Avion_IdAvion = idAvion
         GROUP BY idAvion)leti;
DROP VIEW IF EXISTS najvec_letov;
CREATE VIEW najvec_letov AS
	SELECT ime_model, MAX(st_leta) as maks
	FROM AVION
	JOIN POLET ON idAvion = Avion_idAvion
	GROUP BY idAvion;
    
SELECT * FROM najvec_letov
	WHERE maks = (SELECT MAX(maks)
	FROM najvec_letov);
   
#7.
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM AIRLINE;
UPDATE AIRLINE SET Ime_airline = "Swiss International Air Lines" WHERE Ime_airline = "Swiss International";
SELECT * FROM AIRLINE; 


#8.
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM LOKAL;
DELETE FROM LOKAL WHERE Ime_lokala = "Ljubljancek";
SELECT * FROM LOKAL;

Dodatno vprašanje
SELECT MAX(maks) AS st_lokaloh_na_katerih_je_zaposlen
FROM( 
        SELECT ime_delavca + ' ' + priimek_delavca, MAX(Delavec_idDelavec) AS maks
         FROM DELAVEC,LOKAL WHERE Delavec_idDelavec = idDelavec
         GROUP BY idDelavec)st_poslov;

SELECT MAX(maks) AS st_lokaloh_na_katerih_je_zaposlen
FROM( 
        SELECT ime_delavca + ' ' + priimek_delavca, MAX(st_sluzb) AS maks
         FROM DELAVEC
         GROUP BY idDelavec)st_poslov;

SELECT MAX(maks) AS st_lokaloh_na_katerih_je_zaposlen
FROM( 
        SELECT ime_delavca, priimek_delavca, MAX(st_sluzb) AS maks
         FROM DELAVEC
         GROUP BY idDelavec)st_poslov;
         
SELECT ime_delavca, priimek_delavca, st_sluzb 
FROM DELAVEC

DROP VIEW IF EXISTS najvecje_st_sluzb_delavca;
CREATE VIEW najvecje_st_sluzb_delavca AS
	SELECT ime_delavca, priimek_delavca, MAX(Delavec_idDelavec) as st_sluzb
	FROM DELAVEC
	JOIN LOKAL ON idDelavec = Delavec_idDelavec
	GROUP BY idDelavec;
    
SELECT * FROM najvecje_st_sluzb_delavca
	WHERE st_sluzb = (SELECT MAX(st_sluzb)
	FROM najvecje_st_sluzb_delavca);
    
    










